name: build new type

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11 ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}
    - run: mvn -B install --no-transfer-progress


  publish-snapshot:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up settings.xml for GitHub Packages
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 15

      - name: Publish SNAPSHOT version to GitHub Packages
        run: mvn -B -s $GITHUB_WORKSPACE/.github/workflows/settings.xml  --no-transfer-progress deploy -DskipTests
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PACKAGESREAD_USERNAME: ${{ secrets.PACKAGESREAD_USERNAME }}
         PACKAGESREAD_TOKEN: ${{ secrets.PACKAGESREAD_TOKEN }}           
