name: Call a reusable workflow and use its outputs

on:

  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  job1:
    uses: vinodameta/learning-github-actions/.github/workflows/reusable-wf.yml@main
    
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo done
