name: Call a reusable workflow and use its outputs

on:

  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: false
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo job1 completed
 
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo starting

#Get latest SNAPSHOT releaseVersion from POM.XML
      - name: Get version from POM.XML
        id: getVersion
        run: |
          if [ github.event_name == 'workflow_dispatch' && github.event.inputs.releaseVersion == '' ]
          echo "release=10.10.10" >> "$GITHUB_OUTPUT"
          else 
          echo "you give an input"         
#          [ echo "release=${{ github.event.inputs.releaseVersion }}" >> "$GITHUB_OUTPUT" ]



#Get releaseVersion v${{ github.event.inputs.releaseVersion }}" from Workflow Input
#      - name: Get version from POM.XML
#        if: github.event_name == 'workflow_dispatch' && github.event.inputs.releaseVersion != ''
#        id: getVersion
#        run: |
#          echo "release=${{ github.event.inputs.releaseVersion }}" >> "$GITHUB_OUTPUT"
          
          
#Get releaseVersion v${{ github.event.inputs.releaseVersion }}" from Workflow Input
      - name: Get version 
        run: |
          echo ${{ steps.getVersion.outputs.release }}    
