name: release test-main

on:
#  push:
#    branches:
#      - main
#      - test
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "0.0.1"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "0.0.1-SNAPSHOT"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github

      - name: Configure Git user
        run: |
          git config user.email "vinod.ameta@gmail.com"
          git config user.name "vinodameta"
          
      - name: Publish JAR
        run: mvn release:prepare release:perform -B -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -DreleaseVersion -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PACKAGESREAD_USERNAME: ${{ secrets.PACKAGESREAD_USERNAME }}
         PACKAGESREAD_TOKEN: ${{ secrets.PACKAGESREAD_TOKEN }}   
