name: release test

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 14
          server-id: github
          
      - name: Configure Git user
        run: |
          git config user.email "vinod.ameta@gmail.com"
          git config user.name "vinodameta"
          
      - name: Publish JAR
        run: ./mvnw -B release:prepare release:perform
        env:
         GITHUB_TOKEN: ${{ secrets.PACKAGESREAD_TOKEN }}
         PACKAGESREAD_USERNAME: ${{ secrets.PACKAGESREAD_USERNAME }}
         PACKAGESREAD_TOKEN: ${{ secrets.PACKAGESREAD_TOKEN }}           


      - name: Maven Release x GitHub Packages
        run: |
          git config --global user.name "vinodameta"
          git config --global user.email "vinod.ameta@gmail.com"
          mvn release:prepare  --batch-mode
          mvn release:perform -s $GITHUB_WORKSPACE/.github/workflows/settings.xml
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PACKAGESREAD_USERNAME: ${{ secrets.PACKAGESREAD_USERNAME }}
         PACKAGESREAD_TOKEN: ${{ secrets.PACKAGESREAD_TOKEN }}    
