name: Maven Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: mvn-repo
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn clean install

#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/.github/workflows/settings.xml
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        PACKAGESREAD_USERNAME: ${{ secrets.PACKAGESREAD_USERNAME }}
#        PACKAGESREAD_TOKEN: ${{ secrets.PACKAGESREAD_TOKEN }} 
        
        
    - name: Maven Release x GitHub Packages
      run: |
        git config --global user.name "vinodameta"
        git config --global user.email "vinod.ameta@gmail.com"
        mvn release:prepare 
        mvn release:perform -s $GITHUB_WORKSPACE/.github/workflows/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGESREAD_TOKEN }}
        PACKAGESREAD_USERNAME: ${{ secrets.PACKAGESREAD_USERNAME }}
        PACKAGESREAD_TOKEN: ${{ secrets.PACKAGESREAD_TOKEN }}    
        
